# Generated by Django 6.0.1 on 2026-02-02 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0002_contactmessage_alter_categorymodels_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('preparation_time', models.CharField(max_length=50)),
                ('cooking_time', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=30)),
                ('serves', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('status', models.CharField(choices=[('working', 'Working'), ('published', 'Published')], default='working', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecipeApp.categorymodels')),
            ],
        ),
    ]
